Adds readme (#1)
* Adds readme

* break some files

* configs lint job

* adds stuff

* adapt to bash

* adds sqlite

* minor

* add coverage report

* fix yaml?

* yaml stuff

* hello

* sdf

* skjdhf

* sdf

* asdf

* adfg

* asdjlhf

* asdgasd

* asgasdg

* blkbljb

* asdfasdf

* asdkjhbasdf

* sdfasdf

* adfgdfgsdfg

* asdgasdg

* sdfgsdfg

* asdfasdf

* fasdfdf

* asdfasdf

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -2,42 +2,81 @@ name: GitHub Actions Demo
 run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
 on: [push]
 jobs:
-  Explore-GitHub-Actions:
-    runs-on: ubuntu-latest
-    steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      - name: Check out repository code
-        uses: actions/checkout@v4
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
-      - run: echo "🍏 This job's status is ${{ job.status }}."
   Linter:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - run: mkdir build
-      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
-      - uses: cpp-linter/cpp-linter-action@v2
-        id: linter
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - uses: actions/setup-python@v5
         with:
-          style: 'file'  # Use .clang-format config file
-          tidy-checks: '' # Use .clang-tidy config file
-          # only 'update' a single comment in a pull request's thread.
-          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
-      - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed > 0
-        run: exit 1
-  Build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - run: mkdir build
-      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
-      - run: cmake build --build 
+          python-version: '3.x'
+          cache: 'pip' # caching pip dependencies
+      
+      - uses: ammaraskar/gcc-problem-matcher@master
+
+      - name: Install PIP packages
+        run: pip install -r requirements.txt
+
+      - name: Check code formatting
+        run: clang-format -n -Werror `find src -name '*.cpp'`
+
+      - name: Cmake Configure
+        run: | 
+          mkdir build
+          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+
+      - name: Run clang-tidy (Static analysis & Code style checks)
+        run: clang-tidy -p=build `find src -name '*.cpp'` `find src -name '*.h'`
+
+      - name: Build
+        run: cmake --build build
+
+      - name: Run unit tests
+        run: ./build/src/main --gtest_output=xml:gtest_report.xml
+
+      - name: Generate coverage reports
+        run: |
+          mkdir coverage
+          python3 -m gcovr --filter "src/*" --cobertura cobertura-coverage-details.xml
+          python3 -m gcovr --filter "src/*" --html-details coverage/coverage-details.html
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'gtest_report.xml'
+          include_passed: true
+
+      - name: Code Coverage Report
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: cobertura-coverage-details.xml
+          badge: true
+          fail_below_min: true
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: true
+          indicators: true
+          output: both
+          thresholds: '60 80'
+
+      - name: Add Coverage PR Comment
+        uses: marocchino/sticky-pull-request-comment@v2
+        if: github.event_name == 'pull_request'
+        with:
+          recreate: true
+          path: code-coverage-results.md
+
+      - name: Upload gtest report
+        uses: actions/upload-artifact@v3  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: gtest_report
+          path: gtest_report.xml
+
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v3  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: coverage
+          path: coverage/
